package csw.location.api.commons

private[csw] object Constants {

  // CRDT Key to hold list of all components registered with location service in the form of connection -> location
  val RegistryKey = "location-service-registry"

  // `ClusterName` is used in `ClusterSettings`. It is the name of the cluster to start the akka cluster on.
  val ClusterName = "csw-cluster"

  // `RemoteActorSystemName` is used in `ActorSystemFactory` to create remote ActorSystem with this name
  val RemoteActorSystemName = "csw-remote-actor-system"

  // a constant that plays the componentName in logs generated by location service
  val LocationService = "location-service-lib"
}
