// #register-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Mon, 30 Dec 2019 11:49: 56 GMT
Content-Type: application/json
Content-Length: 151

{
  "HttpLocation": {
    "connection": {
      "prefix": "csw.service",
      "componentType": "service",
      "connectionType": "http"
    },
    "uri": "http://192.168.5.105:1234/root/path1"
  }
}

###
// #register-response

// #other-location-registered-response
HTTP/1.1 500 Internal Server Error
Server: akka-http/10.1.11
Date: Mon, 30 Dec 2019 12: 04: 34 GMT
Content-Type: application/json
Content-Length: 207

{
  "OtherLocationIsRegistered": "there is another location=HttpLocation(HttpConnection(ComponentId(csw.service,Service)),http://192.168.5.105:1235/root/path1) registered against name=csw.service-service-http."
}

###
// #other-location-registered-response

// #bad-request-response
HTTP/1.1 400 Bad Request
Server: akka-http/10.1.11
Date: Mon, 30 Dec 2019 12: 06: 43 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 127

The request content was malformed: Cannot decode `HttpRegistration` instance due to missing map key "port" (input position 208)

###
// #bad-request-response

// #un-register-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 04:46:30 GMT
Content-Type: application/json
Content-Length: 6

"done"

###
// #un-register-response

// #find-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 04: 45: 18 GMT
Content-Type: application/json
Content-Length: 152

[
  {
    "HttpLocation": {
      "connection": {
        "prefix": "csw.server",
        "componentType": "service",
        "connectionType": "http"
      },
      "uri": "http://192.168.5.105:1234/root/path1"
    }
  }
]

###
// #find-response

// #resolve-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 04: 44: 09 GMT
Content-Type: application/json
Content-Length: 152

{
  "HttpLocation": {
    "connection": {
      "prefix": "csw.server",
      "componentType": "service",
      "connectionType": "http"
    },
    "uri": "http://192.168.5.105:1234/root/path1"
  }
}

###
// #resolve-response

// #list-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 04:52:23 GMT
Content-Type: application/json
Content-Length: 152

[
  {
    "HttpLocation": {
      "connection": {
        "prefix": "csw.server",
        "componentType": "service",
        "connectionType": "http"
      },
      "uri": "http://192.168.5.105:1234/root/path1"
    }
  }
]

###
// #list-response

// #list-by-componenttype-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 04:56:52 GMT
Content-Type: application/json
Content-Length: 152

[
  {
    "HttpLocation": {
      "connection": {
        "prefix": "csw.server",
        "componentType": "service",
        "connectionType": "http"
      },
      "uri": "http://192.168.5.105:1234/root/path1"
    }
  }
]

###
// #list-by-componenttype-response

// #list-by-hostname-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 04:57:48 GMT
Content-Type: application/json
Content-Length: 152

[
  {
    "HttpLocation": {
      "connection": {
        "prefix": "csw.server",
        "componentType": "service",
        "connectionType": "http"
      },
      "uri": "http://192.168.5.105:1234/root/path1"
    }
  }
]

###
// #list-by-hostname-response

// #list-by-connectiontype-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 04:59:54 GMT
Content-Type: application/json
Content-Length: 152

[
  {
    "HttpLocation": {
      "connection": {
        "prefix": "csw.server",
        "componentType": "service",
        "connectionType": "http"
      },
      "uri": "http://192.168.5.105:1234/root/path1"
    }
  }
]

###
// #list-by-connectiontype-response

// #list-by-prefix-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 05:00:38 GMT
Content-Type: application/json
Content-Length: 152

[
  {
    "HttpLocation": {
      "connection": {
        "prefix": "csw.server",
        "componentType": "service",
        "connectionType": "http"
      },
      "uri": "http://192.168.5.105:1234/root/path1"
    }
  }
]

###
// #list-by-prefix-response

// #unregister-all-response
HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Tue, 31 Dec 2019 05:00:58 GMT
Content-Type: application/json
Content-Length: 6

"done"

###
// #unregister-all-response