package csw.messages.ccs.commands.matchers

/**
 * Response generated by [[csw.messages.ccs.commands.matchers.Matcher]]
 */
sealed trait MatcherResponse
object MatcherResponses {
  case object MatchCompleted                   extends MatcherResponse
  case class MatchFailed(throwable: Throwable) extends MatcherResponse

  def jMatchCompleted(): MatcherResponse = MatchCompleted
}
