// #register
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "Register": {
    "HttpRegistration": {
      "connection": {
        "prefix": "csw.server",
        "componentType": "service",
        "connectionType": "http"
      },
      "port": 1234,
      "path": "root/path1"
    }
  }
}
###
// #register

// #un-register
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "Unregister": {
    "prefix": "csw.server",
    "componentType": "service",
    "connectionType": "http"
  }
}
###
// #un-register

// #find
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "Find": {
    "prefix": "csw.configserver",
    "componentType": "service",
    "connectionType": "http"
  }
}
###
// #find

// #resolve
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "Resolve": {
    "connection": {
      "prefix": "csw.configserver",
      "componentType": "service",
      "connectionType": "http"
    },
    "within": "5 seconds"
  }
}
###
// #resolve

// #list
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "ListEntries": {}
}
###
// #list

// #list-by-componenttype
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "ListByComponentType": "service"
}
###
// #list-by-componenttype

// #list-by-hostname
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "ListByHostname": "192.168.5.105"
}
###
// #list-by-hostname

// #list-by-connectiontype
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "ListByConnectionType": "tcp"
}
###
// #list-by-connectiontype

// #list-by-prefix
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "ListByPrefix": "csw.eventserver"
}
###
// #list-by-prefix

// #un-register-all
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "UnregisterAll": {}
}
###
// #un-register-all

