package csw.services.alarm.cli.args
import java.io.ByteArrayOutputStream
import java.nio.file.Paths

import csw.messages.params.models.Subsystem.NFIRAOS
import csw.services.BuildInfo
import csw.services.alarm.api.models.AlarmSeverity.Major
import org.scalatest.{FunSuite, Matchers}

class ArgsParserTest extends FunSuite with Matchers {

  //Capture output/error generated by the parser, for cleaner test output. If interested, errCapture.toString will return capture errors.
  private val outCapture = new ByteArrayOutputStream
  private val errCapture = new ByteArrayOutputStream
  private val parser     = new ArgsParser(BuildInfo.name)

  def silentParse(options: Array[String]): Option[Options] = Console.withOut(outCapture) {
    Console.withErr(errCapture) {
      parser.parse(options)
    }
  }

  test("parse without specifying operation") {
    val options = Array("")
    silentParse(options) shouldBe None
  }

  test("parse init command without any options") {
    val options = Array("init")
    silentParse(options) shouldBe None
  }

  test("parse init command with only mandatory options") {
    val options = Array("init", "/a/b/c")
    silentParse(options) should contain(
      Options(cmd = "init", filePath = Some(Paths.get("/a/b/c")))
    )
  }

  test("parse init command with all options") {
    val options = Array("init", "/a/b/c", "--local", "--reset")
    silentParse(options) should contain(
      Options(
        cmd = "init",
        filePath = Some(Paths.get("/a/b/c")),
        isLocal = true,
        reset = true
      )
    )
  }

  test("parse update command without any options") {
    val options = Array("update")
    silentParse(options) shouldBe None
  }

  test("parse update command with all options") {
    val options = Array(
      "update",
      "--subsystem",
      "NFIRAOS",
      "--component",
      "trombone",
      "--name",
      "tromboneAxisHighLimitAlarm",
      "--severity",
      "Major"
    )

    silentParse(options) should contain(
      Options(
        cmd = "update",
        maybeSubsystem = Some(NFIRAOS),
        maybeComponent = Some("trombone"),
        maybeAlarmName = Some("tromboneAxisHighLimitAlarm"),
        severity = Major
      )
    )
  }

  test("parse acknowledge command") {
    val options = Array(
      "acknowledge",
      "--subsystem",
      "NFIRAOS",
      "--component",
      "trombone",
      "--name",
      "tromboneAxisHighLimitAlarm"
    )

    silentParse(options) should contain(
      Options(
        cmd = "acknowledge",
        maybeSubsystem = Some(NFIRAOS),
        maybeComponent = Some("trombone"),
        maybeAlarmName = Some("tromboneAxisHighLimitAlarm")
      )
    )
  }

  test("parse acknowledge command without any options") {
    val options = Array("acknowledge")
    silentParse(options) shouldBe None
  }

  test("parse activate command") {
    val options = Array(
      "activate",
      "--subsystem",
      "nfiraos",
      "--component",
      "trombone",
      "--name",
      "tromboneAxisHighLimitAlarm"
    )

    silentParse(options) should contain(
      Options(
        cmd = "activate",
        maybeSubsystem = Some(NFIRAOS),
        maybeComponent = Some("trombone"),
        maybeAlarmName = Some("tromboneAxisHighLimitAlarm")
      )
    )
  }

  test("parse deactivate command") {
    val options = Array(
      "deactivate",
      "--subsystem",
      "NFIRAOS",
      "--component",
      "trombone",
      "--name",
      "tromboneAxisHighLimitAlarm"
    )

    silentParse(options) should contain(
      Options(
        cmd = "deactivate",
        maybeSubsystem = Some(NFIRAOS),
        maybeComponent = Some("trombone"),
        maybeAlarmName = Some("tromboneAxisHighLimitAlarm")
      )
    )
  }

  test("parse activate/deactivate command without any options") {
    val activateOptions   = Array("activate")
    val deactivateOptions = Array("deactivate")

    silentParse(activateOptions) shouldBe None
    silentParse(deactivateOptions) shouldBe None
  }

  test("parse shelve command") {
    val options = Array(
      "shelve",
      "--subsystem",
      "NFIRAOS",
      "--component",
      "trombone",
      "--name",
      "tromboneAxisHighLimitAlarm"
    )

    silentParse(options) should contain(
      Options(
        cmd = "shelve",
        maybeSubsystem = Some(NFIRAOS),
        maybeComponent = Some("trombone"),
        maybeAlarmName = Some("tromboneAxisHighLimitAlarm")
      )
    )
  }

  test("parse unshelve command") {
    val options = Array(
      "unshelve",
      "--subsystem",
      "NFIRAOS",
      "--component",
      "trombone",
      "--name",
      "tromboneAxisHighLimitAlarm"
    )

    silentParse(options) should contain(
      Options(
        cmd = "unshelve",
        maybeSubsystem = Some(NFIRAOS),
        maybeComponent = Some("trombone"),
        maybeAlarmName = Some("tromboneAxisHighLimitAlarm")
      )
    )
  }

  test("parse shelve/unshelve command without any options") {
    val shelveOptions   = Array("shelve")
    val unshelveOptions = Array("unshelve")
    silentParse(shelveOptions) shouldBe None
    silentParse(unshelveOptions) shouldBe None
  }

  test("parse list command") {
    val options = Array(
      "list",
      "--subsystem",
      "NFIRAOS",
      "--component",
      "trombone",
      "--name",
      "tromboneAxisHighLimitAlarm"
    )

    silentParse(options) should contain(
      Options(
        cmd = "list",
        maybeSubsystem = Some(NFIRAOS),
        maybeComponent = Some("trombone"),
        maybeAlarmName = Some("tromboneAxisHighLimitAlarm")
      )
    )
  }
}
