package csw.messages.params.pb

/**
 * This trait will be mixed in with classes(e.g. StringItems, BooleanItems...etc) generated by ScalaPB.
 */
trait ItemType[T] {

  /**
   * Provides a Seq of values this ItemType holds
   */
  def values: Seq[T]

  /**
   * Create an ItemType with provided values
   *
   * @param values one or more values
   * @return a generic Any type
   */
  def withValues(values: Seq[T]): Any

  /**
   * Create an ItemType with provided values
   *
   * @param values one or more values
   * @return an instance of ItemType
   */
  def set(values: Seq[T]): this.type = withValues(values).asInstanceOf[this.type]
}

/**
 * This trait will be mixed in with companion object of classes generated by ScalaPB.
 */
trait ItemTypeCompanion[S] {
  def defaultInstance: S
}

object ItemTypeCompanion {
  def apply[T](implicit x: ItemTypeCompanion[T]): ItemTypeCompanion[T] = x
  def make[T, S <: ItemType[T]: ItemTypeCompanion](items: Seq[T]): S = {
    ItemTypeCompanion[S].defaultInstance.set(items)
  }
}
