package csw.messages.params.pb

/**
 * This trait will be mixed in with classes(e.g. StringItems, BooleanItems...etc) generated by ScalaPB.
 */
trait ItemType[T] {
  def values: Seq[T]
  def withValues(xs: Seq[T]): Any
  def set(xs: Seq[T]): this.type = withValues(xs).asInstanceOf[this.type]
}

/**
 * This trait will be mixed in with companion object of classes generated by ScalaPB.
 */
trait ItemTypeCompanion[S] {
  def defaultInstance: S
}

object ItemTypeCompanion {
  def apply[T](implicit x: ItemTypeCompanion[T]): ItemTypeCompanion[T] = x
  def make[T, S <: ItemType[T]: ItemTypeCompanion](items: Seq[T]): S = {
    ItemTypeCompanion[S].defaultInstance.set(items)
  }
}
