package csw.messages.commands.matchers

/**
 * Response generated by [[csw.messages.commands.matchers.Matcher]]. The response generated could be
 * [[csw.messages.commands.matchers.MatcherResponses.MatchCompleted]]
 * or [[csw.messages.commands.matchers.MatcherResponses.MatchFailed]]
 */
sealed trait MatcherResponse

object MatcherResponses {

  /**
   * Matcher response indicating the successful matching of demand state
   */
  case object MatchCompleted extends MatcherResponse

  /**
   * Matcher response indicating the failure in matching of demand state
   *
   * @param throwable the error captured in process of matching demand state
   */
  case class MatchFailed private[messages] (throwable: Throwable) extends MatcherResponse

  /**
   * A helper method for java to get the handle of MatchCompleted response
   *
   * @return the instance of MatchCompleted
   */
  def jMatchCompleted(): MatcherResponse = MatchCompleted
}
